# Importing Libraries

In [7]:
# !pip install scikit-learn

In [8]:
# !pip install seaborn

In [9]:
# !pip install matplotlib

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

## Load Data

In [11]:
df = pd.read_csv("./data/American_Housing_Data_202312092.csv")
print(df.shape)
df.head()
df.info()
df.describe(include="all")

(39981, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39981 entries, 0 to 39980
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Zip Code                 39981 non-null  int64
 1   Price                    39981 non-null  float64
 2   Beds                     39981 non-null  int64
 3   Baths                    39981 non-null  int64
 4   Living Space             39981 non-null  int64
 5   Address                  39981 non-null  object
 6   City                     39981 non-null  object
 7   State                    39981 non-null  object
 8   Zip Code Population      39981 non-null  int64
 9   Zip Code Density         39981 non-null  float64
 10  County                   39981 non-null  object
 11  Median Household Income  39979 non-null  float64
 12  Latitude                 39981 non-null  float64
 13  Longitude                39981 non-null  float64
dtypes: float64(5), int64(5), object(4)
memory usage: 4.3+ MB

,Zip Code,Price,Beds,Baths,Living Space,Address,City,State,Zip Code Population,Zip Code Density,County,Median Household Income,Latitude,Longitude
count,39981.000000,3.998100e+04,39981.000000,39981.000000,39981.000000,39981,39981,39981,39981.000000,39981.000000,39981,39979.000000,39981.000000,39981.000000
unique,NaN,NaN,NaN,NaN,NaN,38827,243,29,NaN,NaN,88,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,331 N 127TH ST E,Mesa,California,NaN,NaN,Maricopa,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,20,894,6056,NaN,NaN,1782,NaN,NaN,NaN
mean,64833.391336,6.227771e+05,3.171682,2.466572,1901.522723,NaN,NaN,NaN,37726.201996,2379.412483,NaN,110837.259861,36.435668,-98.080576
std,25614.601116,9.469793e+05,1.308796,1.323042,1211.307257,NaN,NaN,NaN,18672.647445,2946.574792,NaN,47309.055715,4.446862,15.061145
min,10013.000000,1.800000e+03,1.000000,1.000000,2.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,27475.000000,25.729830,-122.826870
25%,40215.000000,2.650000e+05,3.000000,2.000000,1200.000000,NaN,NaN,NaN,24465.000000,902.400000,NaN,76640.000000,33.239850,-111.636310
50%,74136.000000,3.999000e+05,3.000000,2.000000,1639.000000,NaN,NaN,NaN,35049.000000,1588.700000,NaN,100405.000000,36.166620,-96.839680
75%,85730.000000,6.749900e+05,4.000000,3.000000,2265.000000,NaN,NaN,NaN,46816.000000,2736.800000,NaN,135075.000000,39.283090,-85.656980
max,98199.000000,3.800000e+07,54.000000,66.000000,74340.000000,NaN,NaN,NaN,116469.000000,58289.600000,NaN,900203.000000,47.742370,-73.704510

## Data Cleaning

In [13]:
print("Missing values per column:")
print(df.isnull().sum())

print("\nNumber of duplicated rows:")
print(df.duplicated().sum())

Missing values per column:
Zip Code                   0
Price                      0
Beds                       0
Baths                      0
Living Space               0
Address                    0
City                       0
State                      0
Zip Code Population        0
Zip Code Density           0
County                     0
Median Household Income    2
Latitude                   0
Longitude                  0
dtype: int64

Number of duplicated rows:
962

In [14]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()
df["Median Household Income"] = df["Median Household Income"].fillna(df["Median Household Income"].median())

In [15]:
df.shape
df.isnull().sum()

Zip Code                   0
Price                      0
Beds                       0
Baths                      0
Living Space               0
Address                    0
City                       0
State                      0
Zip Code Population        0
Zip Code Density           0
County                     0
Median Household Income    0
Latitude                   0
Longitude                  0
dtype: int64

In [16]:
df.describe()

,Zip Code,Price,Beds,Baths,Living Space,Zip Code Population,Zip Code Density,Median Household Income,Latitude,Longitude
count,39019.000000,3.901900e+04,39019.000000,39019.000000,39019.000000,39019.000000,39019.000000,39019.00000,39019.000000,39019.000000
mean,64870.425818,6.217622e+05,3.171378,2.463748,1899.984187,37697.457905,2367.620880,110786.09949,36.444635,-98.048619
std,25509.952267,9.531520e+05,1.309513,1.325817,1210.783157,18635.871043,2931.105982,47289.87715,4.449218,15.024340
min,10013.000000,1.800000e+03,1.000000,1.000000,2.000000,0.000000,0.000000,27475.00000,25.729830,-122.826870
25%,40218.000000,2.649000e+05,3.000000,2.000000,1201.500000,24440.000000,897.100000,76640.00000,32.996870,-111.634760
50%,74136.000000,3.999000e+05,3.000000,2.000000,1638.000000,35083.000000,1578.800000,100405.00000,36.167890,-96.839430
75%,85716.000000,6.690000e+05,4.000000,3.000000,2265.000000,46816.000000,2727.000000,134948.00000,39.284210,-85.715710
max,98199.000000,3.800000e+07,54.000000,66.000000,74340.000000,116469.000000,58289.600000,900203.00000,47.742370,-73.704510

## Removing Outliers

In [17]:
clean_df = df.copy()

cols_to_clean = ["Price", "Living Space", "Beds", "Baths"]

for col in cols_to_clean:
    lower = clean_df[col].quantile(0.005)
    upper = clean_df[col].quantile(0.995)
    clean_df = clean_df[(clean_df[col] >= lower) & (clean_df[col] <= upper)]
    
clean_df.shape

(38011, 14)